version: 2.1

orbs:
  nx: nrwl/nx@1.7.0

jobs:
  main:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout

      - run:
          name: Start Nx Cloud CI Distribution
          command: pnpm dlx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      - run:
          name: Install PNPM Package Manager
          command: npm install --prefix=$HOME/.local -g pnpm@10

      - run:
          name: Install Project Dependencies
          command: pnpm install --frozen-lockfile

      - nx/set-shas:
          main-branch-name: 'main'

      - run:
          name: Run affected tasks
          command: pnpm exec nx affected --base=$NX_BASE --head=$NX_HEAD -t lint test build e2e-ci

workflows:
  version: 2

  ci:
    jobs:
      - main
